default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: topple_development

test:
  <<: *default
  database: topple_test

production:
  <<: *default
  database: topple_production
  username: topple
  password: <%= ENV['TOPPLE_DATABASE_PASSWORD'] %>
