default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: topple_development

test:
  <<: *default
  database: topple_test

production:
  <<: *default
  database: topple
  username: topple
  password: <%= ENV['TOPPLE_DATABASE_PASSWORD'] %>
